name: Release Automation

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-name: '3.11'
          python-version: '3.11'

      - name: Build Source and Wheel Dist
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Extract Tag Version and Changelog
        id: parse_version
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ steps.parse_version.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
